name: notix
description: Effortlessly manage notifications on Android and iOS with Notix with Firestore integration.
version: 0.0.11
homepage: https://github.com/karrarfalih/notix

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.9.2
  dio: ^5.3.2
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
